name: GitHub CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [8, 8.0.192, 11, 11.0.9, 12, 13, 13.0.4, 14.0.2, 15]
        os: [ubuntu-latest, macOS-latest]
      fail-fast: false
      max-parallel: 4
    name: Build and Test JDK ${{ matrix.java }}, ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
                ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn clean install
      - name: Remove JTS artifacts from cache
        run: |
          find . -name '*.tar.gz' -exec rm {} \;
          rm -rf $HOME/.m2/repository/org/locationtech/jts
